name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install build tool
        run: python -m pip install build

      - name: Build distributions
        run: python -m build

      - id: create_release
        name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Automated release produced by CI. See attached artifacts for wheels/sdist.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload built artifacts to release
        run: |
          echo "Uploading artifacts to release..."
          for f in dist/*; do
            echo "Uploading $f"
            curl -s -X POST \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @"$f" "${{ steps.create_release.outputs.upload_url }}?name=$(basename "$f")"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
